name: ar_bubble_pop
description: A simple AR bubble popping game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  google_mlkit_pose_detection: ^0.10.0
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  sensors_plus: ^4.0.2
  tflite_flutter: ^0.10.4
  image: ^4.5.3
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/ 